<a href="https://colab.research.google.com/github/AnannyaMishra/AnannyaMishra/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

In [21]:
n1=np.array([10,20,30,40])
print(n1)

[10 20 30 40]


In [22]:
n2=np.array([[10,20,30,40],[50,60,70,80]])
print(n2)
print(type(n2))

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>


In [23]:
n3=np.array([[10,20,30,40],[50,60,70,80,90]])
print(n3)

[list([10, 20, 30, 40]) list([50, 60, 70, 80, 90])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [24]:
n4=np.array([[10,20,30,40],[50,60,70,80]])
n4

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [25]:
n5=np.zeros((1,2))
#n5
print(n5)

[[0. 0.]]


In [18]:
n6=np.zeros((5,4))
#n6
print(n6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
n7=np.full((2,2),10)
n7

array([[10, 10],
       [10, 10]])

In [26]:
n8=np.full((3,6),5)
n8

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [27]:
n9=np.arange(10,25)
n9

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
n10=np.arange(10,25,2)
n10

array([10, 12, 14, 16, 18, 20, 22, 24])

In [30]:
n11=np.arange(10,50,5)
#n11
print(n11)

[10 15 20 25 30 35 40 45]


In [31]:
n12=np.arange(10,50)
n12

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [38]:
n13=np.random.randint(1,100,5)
n13

array([34, 54, 70, 63, 21])

In [42]:
n14=np.array([[1,2,3,4,5],[6,7,8,9,10]])
n14.shape

(2, 5)

In [44]:
n14.shape=(5,2)
n14.shape

(5, 2)

In [45]:
n14

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [46]:
n15=np.array([10,20,30])
n16=np.array([40,50,60])
np.vstack((n15,n16))

array([[10, 20, 30],
       [40, 50, 60]])

In [47]:
n17=np.array([10,20,30])
n18=np.array([40,50,60])
np.hstack((n17,n18))

array([10, 20, 30, 40, 50, 60])

In [49]:
n19=np.array([10,20,30])
n20=np.array([40,50,60])
np.column_stack((n19,n20))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [53]:
n21=np.array([10,20,30,40,50,60,70,10])
n22=np.array([50,60,70,80,90,10])
np.intersect1d(n21,n22)

array([10, 50, 60, 70])

In [54]:
n23=np.array([10,20,30,40,50,60])
n24=np.array([50,60,70,80,90])
np.setdiff1d(n23,n24)

array([10, 20, 30, 40])

In [55]:
n25=np.array([10,20,30,40,50,60])
n26=np.array([50,60,70,80,90])
np.setdiff1d(n26,n25)

array([70, 80, 90])

In [58]:
#n27=np.array([10,20,30,40,50,60])
n28=np.array([50,60,70,80,90])
n29=np.array([1,2,3,4,5,6])
np.setdiff1d(n29,n28)

array([1, 2, 3, 4, 5, 6])

In [59]:
n30=np.array([10,20])
n31=np.array([30,40])
np.sum([n30,n31])

100

In [60]:
np.sum([n30,n31],axis=0)

array([40, 60])

In [61]:
np.sum([n30,n31],axis=1)

array([30, 70])